[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "trnrun"
dynamic = ["version"]
description = "Run, monitor, and orchestrate batches of TRNSYS simulations"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=14.2.0",
]
authors = [
    { name = "Natural Resources Canada / Ressources naturelles Canada" },
    { name = "CanmetENERGY in Varennes / CanmetÉNERGIE à Varennes" },
    { name = "Alex Lachance" },
]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering",
    "Typing :: Typed",
]
[project.urls]
Homepage = "https://github.com/NRCan/TRNRun"
Issues = "https://github.com/NRCan/TRNRun/issues"

[dependency-groups]
dev = ["pytest>=9.0.1", "ipykernel>=7.1.0"]

[tool.hatch.version]
path = "trnrun/__init__.py"

[tool.hatch.build.hooks.custom]
path = "hatch_build.py"

[tool.hatch.build.targets.wheel]
packages = ["trnrun"]
artifacts = ["trnrun/bin/trnrun.exe"]

[tool.basedpyright]
pythonVersion = "3.12"
