name = "ProgressTracker-Type3830"
version = "0.4.0"
description = "export simulation TIME, START, STOP and STEP at a set interval"
readme = "README.md"
authors = [
    { name = "Natural Resources Canada / Ressources naturelles Canada" },
    { name = "CanmetENERGY in Varennes / CanmetÉNERGIE à Varennes" },
    { name = "Alex Lachance" },
]
license = {file = '../LICENSE'}
