import std/[sequtils, unittest]

include ../src/monitor


proc fixedTimestamp(): DateTime =
  dateTime(2026, mJun, 19, 19, 37, 13, 0, utc())

proc discardEvent(event: SimulationEvent) {.gcsafe.} =
  discard event

type EventCollector = ref object
  events: seq[SimulationEvent]
  sink: EventSink

proc newEventCollector(): EventCollector =
  result = EventCollector(events: @[])
  let collector = result
  result.sink = proc(event: SimulationEvent) {.gcsafe.} =
    collector.events.add(event)

proc startExitedProcess(): Process =
  startProcess(
    getEnv("COMSPEC"),
    args = ["/c", "exit", "0"],
    options = {poUsePath},
  )

proc removeIfExists(path: string) =
  if fileExists(path):
    removeFile(path)


suite "simulation monitor":
  test "clamps progress to the configured simulation range":
    let mono = getMonoTime()
    let config = SimConfig(
      timestamp: fixedTimestamp(),
      start: 10.0,
      stop: 110.0,
      step: 1.0,
    )

    check SimProgress(mono: mono, time: -5.0).percent(config) == 0.0
    check SimProgress(mono: mono, time: 60.0).percent(config) == 0.5
    check SimProgress(mono: mono, time: 150.0).percent(config) == 1.0

    let invalidConfig = SimConfig(start: 10.0, stop: 10.0)
    check SimProgress(mono: mono, time: 10.0).percent(invalidConfig) == 0.0

  test "calculates elapsed time and ETA from monotonic time":
    let
      start = getMonoTime()
      progressTime = start + initDuration(milliseconds = 1_000)
      config = SimConfig(start: 0.0, stop: 100.0)
      halfway = SimProgress(mono: progressTime, time: 50.0)
      negligible = SimProgress(mono: progressTime, time: 0.05)
      complete = SimProgress(mono: progressTime, time: 100.0)

    check halfway.elapsed(start) == 1_000.0
    check halfway.eta(config, start) == 1_000.0
    check negligible.eta(config, start) == 0.0
    check complete.eta(config, start) == 0.0

  test "splits key-value lines at the first colon":
    check splitKeyValue(" Message : first: second ") ==
      (key: "Message", val: "first: second")
    check splitKeyValue("no separator") == (key: "", val: "")
    check splitValue("Generated by Unit : 5") == "5"

  test "groups log lines into header-led blocks":
    let blocks = toSeq(logBlocks([
      "ignored preamble",
      "*** Notice at time : 0",
      "Message : first",
      "*** Warning at time : 1",
      "Generated by Unit : 5",
      "Message : second",
    ]))

    check blocks == @[
      @["*** Notice at time : 0", "Message : first"],
      @[
        "*** Warning at time : 1",
        "Generated by Unit : 5",
        "Message : second",
      ],
    ]

  test "parses every supported log field":
    let parsed = parseLogBlock([
      "*** Warning at time : 24.5",
      "Generated by Unit : 5",
      "Generated by Type : 139",
      "TRNSYS Message 101 : Example warning",
      "Reported information : Example details",
    ])

    check parsed.isSome
    let entry = parsed.get()
    check entry.severity == Warning
    check entry.time == 24.5
    check entry.unitId == some(5)
    check entry.typeId == some(139)
    check entry.messageCode == some(101)
    check entry.message == some("Example warning")
    check entry.information == some("Example details")

  test "ignores unavailable and malformed log fields":
    let ignored = parseLogBlock([
      "*** Fatal at time : 10",
      "Generated by Unit : Not applicable",
      "Generated by Type : invalid",
      "TRNSYS Message invalid : Not available",
      "Information : Not applicable or not available",
    ])

    check ignored.isSome
    let entry = ignored.get()
    check entry.severity == Fatal
    check entry.time == 10.0
    check entry.unitId.isNone
    check entry.typeId.isNone
    check entry.messageCode.isNone
    check entry.message.isNone
    check entry.information.isNone
    check parseLogBlock(["Message : no header"]).isNone

  test "reads only newly completed log lines":
    let path = getTempDir() / "trnrun_monitor_new_lines.log"
    removeIfExists(path)
    defer: removeIfExists(path)

    writeFile(path, "first\npartial")
    var offset = 0'i64

    check readNewLines(offset, path) == @["first"]
    check offset == 6

    writeFile(path, "first\npartial line\nsecond\r\n")
    check readNewLines(offset, path) == @["partial line", "second"]
    check readNewLines(offset, path) == newSeq[string]()

    writeFile(path, "new\n")
    check readNewLines(offset, path) == @["new"]
    check offset == 4

  test "parses appended log entries and advances the offset":
    let path = getTempDir() / "trnrun_monitor_entries.log"
    removeIfExists(path)
    defer: removeIfExists(path)

    writeFile(
      path,
      "*** Notice at time : 0\n" &
      "Message : Started\n" &
      "*** Fatal at time : 12.5\n" &
      "TRNSYS Message 999 : Stopped\n",
    )

    var
      offset = 0'i64
      entries = newSeq[SimLog]()
    for entry in readLog(offset, path):
      entries.add(entry)

    check entries.len == 2
    check entries[0].severity == Notice
    check entries[0].message == some("Started")
    check entries[1].severity == Fatal
    check entries[1].time == 12.5
    check entries[1].messageCode == some(999)
    check offset == getFileSize(path)

  test "parses valid TMP content and rejects malformed content":
    let parsed = parseTmpContent(" 24.5, 0, 8760, 0.25 \n")

    check parsed.isSome
    let snapshot = parsed.get()
    check snapshot.progress.time == 24.5
    check snapshot.config.start == 0.0
    check snapshot.config.stop == 8760.0
    check snapshot.config.step == 0.25

    check parseTmpContent("1, 2, 3").isNone
    check parseTmpContent("current, 0, 100, 1").isNone

  test "reads TMP snapshots and treats I/O errors as unavailable":
    let path = getTempDir() / "trnrun_monitor_snapshot.tmp"
    removeIfExists(path)
    defer: removeIfExists(path)

    check readTmp(path).isNone

    writeFile(path, "50, 0, 100, 1")
    let snapshot = readTmp(path)
    check snapshot.isSome
    check snapshot.get().progress.time == 50.0

  test "emits config once and progress only when simulation time changes":
    let path = getTempDir() / "trnrun_monitor_poll.tmp"
    removeIfExists(path)
    defer: removeIfExists(path)

    let collector = newEventCollector()
    let start = getMonoTime() - initDuration(milliseconds = 1_000)
    var state = MonitorState(
      tmpFile: path,
      processStartTime: start,
      eventSink: collector.sink,
      lastProgressChange: start,
    )

    writeFile(path, "10, 0, 100, 1")
    state.pollTmp()
    check collector.events.len == 2
    check collector.events[0].kind == eventConfig
    check collector.events[1].kind == eventProgress
    check collector.events[1].progressData.time == 10.0

    state.pollTmp()
    check collector.events.len == 2

    writeFile(path, "20, 0, 100, 1")
    state.pollTmp()
    check collector.events.len == 3
    check collector.events[2].kind == eventProgress
    check collector.events[2].progressData.time == 20.0

    let lastAdvance = state.lastProgressChange
    writeFile(path, "15, 0, 100, 1")
    state.pollTmp()
    check collector.events.len == 4
    check state.lastProgressChange == lastAdvance

  test "filters log events by severity and reports fatal entries":
    let path = getTempDir() / "trnrun_monitor_poll.log"
    removeIfExists(path)
    defer: removeIfExists(path)

    writeFile(
      path,
      "*** Notice at time : 0\n" &
      "Message : notice\n" &
      "*** Warning at time : 1\n" &
      "Message : warning\n" &
      "*** Fatal at time : 2\n" &
      "Message : fatal\n",
    )

    let collector = newEventCollector()
    var state = MonitorState(
      logFile: path,
      watchLog: true,
      severity: Warning,
      eventSink: collector.sink,
    )

    check state.pollLog()
    check collector.events.len == 2
    check collector.events[0].logData.severity == Warning
    check collector.events[1].logData.severity == Fatal

  test "evaluates timeout and stall thresholds":
    let start = getMonoTime()
    var state = MonitorState(
      monitorStartTime: start,
      watchTimeoutMs: 100,
      watchTmp: true,
      stallTimeoutMs: 200,
      lastProgressChange: start,
      lastSnapshot: some(TmpSnapshot(
        config: SimConfig(start: 0.0, stop: 100.0),
        progress: SimProgress(mono: start, time: 50.0),
      )),
    )

    check not state.isTimedOut(start + initDuration(milliseconds = 99))
    check state.isTimedOut(start + initDuration(milliseconds = 100))
    check not state.isStalled(start + initDuration(milliseconds = 199))
    check state.isStalled(start + initDuration(milliseconds = 200))

    state.lastSnapshot = some(TmpSnapshot(
      config: SimConfig(start: 0.0, stop: 100.0),
      progress: SimProgress(mono: start, time: 100.0),
    ))
    check not state.isStalled(start + initDuration(milliseconds = 500))

  test "clamps positive timeout thresholds to the polling interval":
    check clampTimeout(0, 100, "timeout") == 0
    check clampTimeout(100, 100, "timeout") == 100
    check clampTimeout(50, 100, "timeout") == 100
    check clampTimeout(200, 100, "timeout") == 200

  test "returns done when an unwatched process exits normally":
    let
      deckPath = getTempDir() / "trnrun_monitor_done.dck"
      logPath = deckPath.changeFileExt("log")
      process = startExitedProcess()
      sink: EventSink = discardEvent
    removeIfExists(logPath)
    defer:
      process.close()
      removeIfExists(logPath)

    check monitor(
      process,
      deckPath,
      getMonoTime(),
      sink,
      watchLog = false,
      watchTmp = false,
    ) == simDone

  test "detects fatal logs after an unwatched process exits":
    let
      deckPath = getTempDir() / "trnrun_monitor_fatal.dck"
      logPath = deckPath.changeFileExt("log")
      process = startExitedProcess()
      sink: EventSink = discardEvent
    removeIfExists(logPath)
    defer:
      process.close()
      removeIfExists(logPath)

    writeFile(
      logPath,
      "*** Fatal at time : 0\n" &
      "Message : Simulation failed\n",
    )

    check monitor(
      process,
      deckPath,
      getMonoTime(),
      sink,
      watchLog = false,
      watchTmp = false,
    ) == simFatal
